name: Microservice
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:latest
      env:
        PROTOBUF_VERSION: 3.12.3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Buf
      run: make local
    - name: Download
      run: GO111MODULE=off go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    - name: Setup
      run: make setup
    - name: Generate
      run: make generate
    - name: Build
      run: CGO_ENABLED=0 go build -v
